// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: file_handler.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Method int32

const (
	Method_CREATE Method = 0
	Method_DELELT Method = 1
	Method_READ   Method = 3
	Method_WRITE  Method = 4
)

// Enum value maps for Method.
var (
	Method_name = map[int32]string{
		0: "CREATE",
		1: "DELELT",
		3: "READ",
		4: "WRITE",
	}
	Method_value = map[string]int32{
		"CREATE": 0,
		"DELELT": 1,
		"READ":   3,
		"WRITE":  4,
	}
)

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}

func (x Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Method) Descriptor() protoreflect.EnumDescriptor {
	return file_file_handler_proto_enumTypes[0].Descriptor()
}

func (Method) Type() protoreflect.EnumType {
	return &file_file_handler_proto_enumTypes[0]
}

func (x Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Method.Descriptor instead.
func (Method) EnumDescriptor() ([]byte, []int) {
	return file_file_handler_proto_rawDescGZIP(), []int{0}
}

type ChunckHandler struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkServiceAddress string `protobuf:"bytes,1,opt,name=chunkServiceAddress,proto3" json:"chunkServiceAddress,omitempty"`
	Method              Method `protobuf:"varint,2,opt,name=method,proto3,enum=Method" json:"method,omitempty"`
	Permitted           bool   `protobuf:"varint,3,opt,name=permitted,proto3" json:"permitted,omitempty"`
}

func (x *ChunckHandler) Reset() {
	*x = ChunckHandler{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_handler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChunckHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunckHandler) ProtoMessage() {}

func (x *ChunckHandler) ProtoReflect() protoreflect.Message {
	mi := &file_file_handler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunckHandler.ProtoReflect.Descriptor instead.
func (*ChunckHandler) Descriptor() ([]byte, []int) {
	return file_file_handler_proto_rawDescGZIP(), []int{0}
}

func (x *ChunckHandler) GetChunkServiceAddress() string {
	if x != nil {
		return x.ChunkServiceAddress
	}
	return ""
}

func (x *ChunckHandler) GetMethod() Method {
	if x != nil {
		return x.Method
	}
	return Method_CREATE
}

func (x *ChunckHandler) GetPermitted() bool {
	if x != nil {
		return x.Permitted
	}
	return false
}

var File_file_handler_proto protoreflect.FileDescriptor

var file_file_handler_proto_rawDesc = []byte{
	0x0a, 0x12, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x01, 0x0a, 0x0d, 0x43, 0x68, 0x75, 0x6e, 0x63, 0x6b, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x13, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x13, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x65, 0x72,
	0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x2a, 0x35, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x44, 0x45, 0x4c, 0x45, 0x4c, 0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x45, 0x41,
	0x44, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x52, 0x49, 0x54, 0x45, 0x10, 0x04, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_file_handler_proto_rawDescOnce sync.Once
	file_file_handler_proto_rawDescData = file_file_handler_proto_rawDesc
)

func file_file_handler_proto_rawDescGZIP() []byte {
	file_file_handler_proto_rawDescOnce.Do(func() {
		file_file_handler_proto_rawDescData = protoimpl.X.CompressGZIP(file_file_handler_proto_rawDescData)
	})
	return file_file_handler_proto_rawDescData
}

var file_file_handler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_file_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_file_handler_proto_goTypes = []interface{}{
	(Method)(0),           // 0: Method
	(*ChunckHandler)(nil), // 1: ChunckHandler
}
var file_file_handler_proto_depIdxs = []int32{
	0, // 0: ChunckHandler.method:type_name -> Method
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_file_handler_proto_init() }
func file_file_handler_proto_init() {
	if File_file_handler_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_file_handler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChunckHandler); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_file_handler_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_handler_proto_goTypes,
		DependencyIndexes: file_file_handler_proto_depIdxs,
		EnumInfos:         file_file_handler_proto_enumTypes,
		MessageInfos:      file_file_handler_proto_msgTypes,
	}.Build()
	File_file_handler_proto = out.File
	file_file_handler_proto_rawDesc = nil
	file_file_handler_proto_goTypes = nil
	file_file_handler_proto_depIdxs = nil
}
